apiVersion: v1
kind: Pod
metadata:
 name: purple
spec:
 containers:
#container 1- the busybox service
   - command:
     - sh
     - -c
     - echo The Appis running! && sleep 5
     image: busybox:latest
     name: purple-container

#init container 1 testing sleep.
   - commnad:
     - sh
     - -c
     - sleep 10
     image: busybox:latest
     name: warm-up1
#init container 2 testing sleep using commands in brackets
   - command: ["sh", "-c", "sleep 20"]
     image: busybox:latest
     name: warm-up2

