apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
spec:
  #Using Node labels
  nodeSelector:
     disktype: ssd  
  containers:
  - image: nginx
    name: pod
    ports:
    - containerPort: 80
