apiVersion: v1
kind: Pod
metadata:
  name: node-name-pod
spec:
  #Using Node Name
  nodeName: worker-node-1.example.com 
  containers:
  - image: nginx
    name: pod
    ports:
    - containerPort: 80
