apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  labels:
    app: wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.47.128
    path: "/mydbdata"

