apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  creationTimestamp: null
  labels:
    app: postgres
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels: 
        app: postgres
    spec: 
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: mypw
        - name: POSTGRES_DB
          value: myfirstdb
        resources: {}
status: {}
